# Generated by Django 3.1.6 on 2021-02-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('address', models.CharField(max_length=20)),
                ('contactno', models.IntegerField(primary_key=True, serialize=False)),
                ('emailaddress', models.CharField(max_length=15)),
                ('qualification', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('keyskills', models.CharField(max_length=200)),
                ('regdate', models.CharField(max_length=30)),
            ],
        ),
    ]
