# Generated by Django 3.1.6 on 2021-02-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificationtext', models.CharField(max_length=200)),
                ('notificationdate', models.CharField(max_length=30)),
            ],
        ),
    ]
